spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:auth0lite}
    username: ${POSTGRES_USER:auth0lite}
    password: ${POSTGRES_PASSWORD:changeme}

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.github.deshenrao.auth0lite: DEBUG
